FrontMVC/Models/ManagerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TaxiDTO.DTO;

namespace FrontMVC.Models
{
    public class ManagerViewModel
    {
        public ManagerViewModel()
        {

        }

        public ManagerViewModel(ManagerDTO manager)
        {
            Id = manager.Id;
            Name = manager.Name;
            Surname = manager.Surname;
            Cpf = manager.Cpf;
            Email = manager.Email;
            Password = manager.Password;
        }

        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Surname { get; set; }
     
        [Required]
        public string Cpf { get; set; }
        
        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

FrontMVC/Models/ManagersViewModel.cs
using System.Collections.Generic;
using TaxiDTO.DTO;

namespace FrontMVC.Models
{
    public class ManagersViewModel
    {
        public List<ManagerResponse> Managers { get; set; }
        public ManagersViewModel(List<ManagerResponse> managers)
        {
            Managers = managers;
        }
    }
}

FrontMVC/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrontMVC.Models;
using FrontMVC.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaxiDTO.DTO;

namespace FrontMVC.Controllers
{
    public class ManagerController : Controller
    {
        protected readonly IApiClient _apiClient;


        public ManagerController(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        [HttpGet]
        public JsonResult GetManagers()
        {
            ManagersViewModel viewModel = new ManagersViewModel(_apiClient.GetManagersAsync().Result);
            return Json(viewModel);
        }

        [HttpGet]
        public JsonResult GetManager(int id)
        {
            ManagerViewModel viewModel = new ManagerViewModel(_apiClient.GetManagerByIdAsync(id).Result);
            return Json(viewModel);
        }
        // GET: Manager
        public ActionResult Index()
        {
            //Carregados via Ajax
            //ManagersViewModel viewModel = new ManagersViewModel(_apiClient.GetManagersAsync().Result);
            return View();
        }

        // GET: Manager/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Manager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Manager/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManagerViewModel manager)
        {
            /*try
            {*/
                ManagerDTO m = new ManagerDTO
                {
                    Name = manager.Name,
                    Surname = manager.Surname,
                    Email = manager.Email,
                    Cpf = manager.Cpf,
                    Password = manager.Password != null ? manager.Password : "",
                    AdministratorId = 1
                };

                if (_apiClient.AddManagerAsync(m).Result)
                {

                }

                return RedirectToAction(nameof(Index));
            /*}
            catch
            {
                return View();
            }*/
        }

        // GET: Manager/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Manager/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Manager/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Manager/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontMVC/Views/Manager/Index.cshtml
@model ManagerViewModel
@{
    ViewData["Title"] = "Home Page";
}
<h1 class="display-4">Gerentes</h1>
<div class="row">
    <div class="col-12 mt-2">
        <table id="manager-table" class="table mt-4">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sobrenome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Administrador</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#managerDialog">
            Novo Gerente
        </button>
        <a id="reload" class="btn btn-secondary">reload</a>
    </div>
</div>

<div id="managerDialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Novo Gerente</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Manager", FormMethod.Post, new { id = "manager-form" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" onclick="$('#manager-form').submit();" class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            reloadTable();

            $("#manager-form").submit(function (e) {
                e.preventDefault();
                $(this).validate();
                if($(this).valid()){
                    var form = $(this);
                    var url = form.attr('action');
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: form.serialize(),
                        success: function (data) {
                            $('#managerDialog').modal('hide');
                            reloadTable();
                        }
                    });
                }
            });

            function reloadTable(){
                $.ajax({
                    type: "GET",
                    dataType: 'json',
                    url: '@Url.Action("GetManagers", "Manager")',
                    success: function (data) {
                        var table = $('#manager-table tbody');
                        table.html('');
                        $.each(data.managers, function(k,v){
                            var tr = $('<tr>');
                            tr.append('<th scope="row"><a href="#" class="update" data-id="'+v.id+'">'+v.id+'</a></th>');
                            tr.append('<td>'+v.name+'</td>');
                            tr.append('<td>'+v.surname+'</td>');
                            tr.append('<td>'+v.cpf+'</td>');
                            tr.append('<td>'+v.email+'</td>');
                            tr.append('<td>'+v.administrator.name+'</td>');
                            table.append(tr);
                        })
                        set_update_triggers();
                    }
                });
            }

            function set_update_triggers() {
                $('.update').click(function () {
                    var id = $(this).data('id');
                    console.log(id);
                    $.ajax({
                        type: "GET",
                        dataType: 'json',
                        data: { id: id },
                        url: '@Url.Action("GetManager", "Manager")',
                        success: function (data) {
                            console.log(data);
                            var modal = $('#managerDialog .modal-body');
                            modal.find('input[name=Name]').val(data.name);
                            modal.find('input[name=Surname]').val(data.surname);
                            modal.find('input[name=Cpf]').val(data.cpf);
                            modal.find('input[name=Email]').val(data.email);
                            modal.find('input[name=Password]').parent().hide();
                            $('#managerDialog').modal('show');
                        }
                    });
                });
            }

            $('#managerDialog').on('hidden.bs.modal', function () {
                $("#manager-form").trigger('reset');
                $(this).find('input[name=Password]').parent().show();
            });
        });
    </script>
}